### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hphilipp** [hphilipp/draw#1]
- [x] AppIcon Designen
- [x] Abfrage bei komplettem Bild löschen
- [x] Popup, wenn Bild gespeichert wurde
- [x] Hintergrundbild einfügen
- [x] Farbe vom Hintergrund ändern
- [x] Radiergummi (transparent malen?)
- [x] ColorPicker und LineWidthPicker zentrieren

**Comment by hphilipp** [comment]
- [x] Hintergrundfarbe mit Delegate funktioniert noch nicht ganz
- [x] Hintergrundbild Größe anpassen
- [x] Performance bei Hintergrund als Farbe ziemlich schlecht
- [x] Redo auch mit Liste

**Comment by hphilipp** [comment]
- [x] Colorpicker in Settings zentrieren
- [x] Bild nur in Breite anpassen, Verhältnis beibehalten 
- [x] wenn Hintergrund ausgewählt, dann der Radiergummi ausgewählt und dann Hintergrund geändert wird, bleibt der Radiergummi in alter Farbe
- [x] Wenn Hintergrund geladen wird, alle Striche löschen (mit Abfrage), da sonst die radiergummistriche auffallen
- [x] Abfrage ob Hintergrund überschrieben werden soll in Settings und view
- [x] Zentrierung wenn app gedreht wird (auf settings geht nicht alles drauf)
    -> Drehung der App verhindern, da nicht sinnvoll für Funktionalität der App
- [x] Hintergrund durch Kamera
- [x] 3d-Touch Shortcut für Hintergrund Kamera und Hintergrund durch Bild aus Album

**Comment by hphilipp** [comment]
- [] wenn Hintergrund ausgewählt, dann Radiergummi ausgewählt und dann Hintergrund geändert wird, bleibt der Radiergummi in alter Farbe

**Comment by hphilipp** [comment]
Wenn Hintergrund geladen wird, alle Striche löschen (mit Abfrage), da sonst die radiergummistriche auffallen

Abfrage ob Hintergrund überschrieben werden soll in Settings und view
